### ISSUE TITLE
Graceful shutdown

### ISSUE THREAD

**Issue by rutchkiwi** [luminus-framework/ring-undertow-adapter#33]
When shutting down the server, the current behaviour is just to cut off any in-progress requests, with an "empty reply form server".
This is not very nice to any clients waiting for a response, as they just get an error.

A better solution is to have a graceful shutdown, where any in-flight requests get some amount of time to complete. (new requests should be rejected). 
Http-kit, which I'm switching from, [has this feature](https://github.com/http-kit/http-kit/wiki/3-Server#stop-server).

I found undertow documentation about [GracefulShutdownHandler](https://undertow.io/javadoc/1.3.x/io/undertow/server/handlers/GracefulShutdownHandler.html) but I'm unsure how to integrate that. Is it possible as is, using the `:configurator` option? Best would be to handle this in this adapter, either with a `:shutdown-timeout` option, or as a parameter to `.stop`.

Also, thanks for a nice library :)

**Comment by rutchkiwi** [comment]
Also, when you do shut down with requests in-flight, you get an error: 

```
12:31:20.523 ERROR [] io.undertow.request - UT005071: Undertow request failed HttpServerExchange{ GET /bing-feed.txt}
java.lang.IllegalStateException: UT000002: The response has already been started
	at io.undertow.server.HttpServerExchange.setStatusCode(HttpServerExchange.java:1487)
	at ring.adapter.undertow.response$set_exchange_response.invokeStatic(response.clj:57)
	at ring.adapter.undertow.response$set_exchange_response.invoke(response.clj:52)
	at ring.adapter.undertow$handle_request.invokeStatic(undertow.clj:23)
	at ring.adapter.undertow$handle_request.invoke(undertow.clj:19)
	at ring.adapter.undertow$undertow_handler$fn$reify__15916.handleRequest(undertow.clj:41)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:393)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:859)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by nikolap** [comment]
FYI @rutchkiwi have a PR open with a draft solution. It is a technically breaking change if you're using the lib a certain way, but for most people should not be breaking. Feel free to give it a spin and let me know if it resolves your issues.

All you need to do is add `:graceful-shutdown-timeout` to the undertow config with the ms of timeout

**Comment by nikolap** [comment]
@rutchkiwi you can now use this with [1.4.0](https://clojars.org/luminus/ring-undertow-adapter) 🎉

**Comment by rutchkiwi** [comment]
Thank you @nikolap, this is great! I'm already working on switching out servers over. :)
